package com.hospital.pharmacy.exception;

public enum ErrorCode {
    TRACE_CODE_DUPLICATED,
    STOCK_CONFLICT,
    INVALID_STATE_TRANSITION,
    PRESCRIPTION_MISMATCH,
    IDEMPOTENT_REPLAY,
    IDEMPOTENT_PROCESSING,
    IDEMPOTENT_CONFLICT,
    HIS_MAPPING_REQUIRED,
    HIS_REVISION_CONFLICT,
    HIS_RETURN_REQUIRED,
    BAD_REQUEST
}
